version: 2
jobs:
 version-prod:
    working_directory: /project/workspace/
    docker:
      - image: lakhanmandloi/docker-ubuntu-ruby-python-npm:2.0
    steps:

      # Checkout
      - checkout

      # Add SSH Key
      - add_ssh_keys:
          fingerprints:
            - $GITHUB_SSH_FINGERPRINT

      # Configure Git
      - type: shell
        name: Configure git
        command: |
          git config --global user.email $GITHUB_USER_EMAIL
          git config --global user.name $GITHUB_USER_NAME

      # Download code from staging
      - type: shell
        name: Download code from staging
        command: |
          cd ..
          rm -rf downloads
          mkdir downloads
          cd downloads
          aws s3 sync --delete s3://sunbird-docs-qa/docs-staging/$CIRCLE_BRANCH/ .
          ls -la

      # Deploy to Gitpages
      - type: shell
        name: Deploy code to gh-pages repo
        command: |
          cd ..
          rm -rf deploy
          mkdir deploy
          cd deploy
          git clone -b gh-pages $CIRCLE_REPOSITORY_URL cloned-repo
          rm -rf cloned-repo/$CIRCLE_BRANCH/
          mkdir cloned-repo/$CIRCLE_BRANCH/
          cp -R ../downloads/* cloned-repo/$CIRCLE_BRANCH/
          cd cloned-repo/
          git add -A
          git commit -m "Version deploy - $CIRCLE_BRANCH Version & Build No. $CIRCLE_BUILD_NUM"
          git push origin gh-pages

workflows:
  version: 2
  version-build-deploy:
    jobs:
      - version-prod:
          filters:
            branches:
              ignore:
                - gh-pages
                - toc
                - /^pull.*/


